# Generated by Django 5.2.7 on 2025-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SSV Academy', max_length=100)),
                ('description', models.TextField(default='Learn the art of Aari embroidery from expert women trainers.')),
                ('feature1', models.CharField(default='Beginner | Intermediate | Premium Bridal Courses', max_length=100)),
                ('feature2', models.CharField(default='Online & Offline learning', max_length=100)),
                ('feature3', models.CharField(default='Certification & gallery showcase', max_length=100)),
                ('button_text', models.CharField(default='Enroll Now', max_length=50)),
                ('button_url', models.CharField(default='/academy/', max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='arrivals/')),
                ('button_text', models.CharField(default='View Details', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-hand-sparkles', help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(default='100% Handcrafted', max_length=100)),
                ('description', models.TextField(default='By Skilled Women Artisans')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gallery Item', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Crafting Dreams into Reality', help_text='Main hero title', max_length=200)),
                ('subtitle', models.TextField(default='Experience the timeless artistry of traditional AARI embroidery.', help_text='Hero subtitle/description')),
                ('primary_button_text', models.CharField(default='Explore Collections', max_length=50)),
                ('primary_button_url', models.CharField(default='/collections/', max_length=100)),
                ('secondary_button_text', models.CharField(default='Get Quote', max_length=50)),
                ('secondary_button_url', models.CharField(default='/contact/', max_length=100)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-tshirt', help_text='FontAwesome icon class (e.g., fas fa-tshirt)', max_length=50)),
                ('title', models.CharField(default='Custom Tailored Blouses', max_length=100)),
                ('description', models.TextField(default='Perfect fit with unique embroidery')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='websitecontent',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='features',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='collection',
            name='button_text',
            field=models.CharField(default='Explore Collection', max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='button_url',
            field=models.CharField(default='/collections/', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='Basic Collection', max_length=100),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='WebsiteContent',
        ),
    ]
