# Generated by Django 5.2.7 on 2025-10-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academysection_arrival_feature_galleryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Experience Authentic AARI Embroidery?', max_length=200)),
                ('subtitle', models.TextField(default='Join us in celebrating traditional craftsmanship...')),
                ('primary_button_text', models.CharField(default='Explore Collections', max_length=50)),
                ('primary_button_url', models.CharField(default='/collections/', max_length=100)),
                ('secondary_button_text', models.CharField(default='Contact Us', max_length=50)),
                ('secondary_button_url', models.CharField(default='/contact/', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About SVV Aari Work', help_text='Main hero title', max_length=200)),
                ('subtitle', models.TextField(default='Discover the story behind our passion for traditional AARI embroidery.', help_text='Hero subtitle')),
                ('years_experience', models.PositiveIntegerField(default=15)),
                ('designs_completed', models.PositiveIntegerField(default=1000)),
                ('happy_clients', models.PositiveIntegerField(default=500)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='about/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='To preserve the traditional art of AARI embroidery...')),
                ('mission_icon', models.CharField(default='fas fa-bullseye', max_length=50)),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='To become a global leader in authentic AARI embroidery...')),
                ('vision_icon', models.CharField(default='fas fa-eye', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-clock', help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(default='15+ Years Experience', max_length=100)),
                ('description', models.TextField(default='Master artisans with decades of expertise')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=100)),
                ('main_text', models.TextField(default='Founded with a vision to preserve traditional AARI embroidery...')),
                ('secondary_text', models.TextField(default='What started as a small initiative has grown into a comprehensive platform...')),
                ('value1_icon', models.CharField(default='fas fa-heart', max_length=50)),
                ('value1_title', models.CharField(default='Women Empowerment', max_length=100)),
                ('value2_icon', models.CharField(default='fas fa-gem', max_length=50)),
                ('value2_title', models.CharField(default='Traditional Craft', max_length=100)),
                ('value3_icon', models.CharField(default='fas fa-globe', max_length=50)),
                ('value3_title', models.CharField(default='Cultural Heritage', max_length=100)),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/story/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-leaf', help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(default='Sustainability', max_length=100)),
                ('description', models.TextField(default='Eco-friendly practices and materials')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
