# Generated by Django 5.2.7 on 2025-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutcta_aboutherosection_aboutmissionvision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-infinity', help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(default='Lifetime Access', max_length=100)),
                ('description', models.TextField(default='Video tutorials for online students')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('title', models.CharField(default='Beginner Aari Course', max_length=100)),
                ('duration', models.CharField(default='4 Weeks', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=2500.0, max_digits=8)),
                ('description', models.TextField(default='Perfect for absolute beginners. Learn the fundamentals of Aari embroidery.')),
                ('schedule', models.CharField(default='Mon–Wed–Fri, 10 AM – 12 PM', max_length=100)),
                ('feature1', models.CharField(default='Basic stitching techniques', max_length=100)),
                ('feature2', models.CharField(default='Thread handling & fabric preparation', max_length=100)),
                ('feature3', models.CharField(default='Simple floral patterns', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/courses/')),
                ('enrollment_url', models.URLField(default='https://wa.me/+917639027885')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Start Your AARI Journey?', max_length=200)),
                ('subtitle', models.TextField(default='Join hundreds of students who have discovered their passion for AARI embroidery')),
                ('button_text', models.CharField(default='Contact for Enrollment', max_length=50)),
                ('button_url', models.URLField(default='https://wa.me/+917639027885')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SSV Academy', help_text='Main hero title', max_length=200)),
                ('subtitle', models.TextField(default='Master the art of AARI embroidery from master craftsmen.', help_text='Hero subtitle')),
                ('course_levels', models.PositiveIntegerField(default=4)),
                ('students_trained', models.PositiveIntegerField(default=500)),
                ('certification_rate', models.PositiveIntegerField(default=100)),
                ('background_image', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='academy/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Master the Art of AARI', max_length=200)),
                ('main_text', models.TextField(default='At SSV Academy, we believe that the beauty of AARI embroidery should be shared with the world.')),
                ('feature1_icon', models.CharField(default='fas fa-user-graduate', max_length=50)),
                ('feature1_title', models.CharField(default='Expert Instructors', max_length=100)),
                ('feature1_description', models.TextField(default='Learn from master craftsmen with decades of experience')),
                ('feature2_icon', models.CharField(default='fas fa-hands-helping', max_length=50)),
                ('feature2_title', models.CharField(default='Hands-on Learning', max_length=100)),
                ('feature2_description', models.TextField(default='Practical training with real materials and techniques')),
                ('feature3_icon', models.CharField(default='fas fa-users', max_length=50)),
                ('feature3_title', models.CharField(default='Small Class Sizes', max_length=100)),
                ('feature3_description', models.TextField(default='Personalized attention in intimate learning environments')),
                ('feature4_icon', models.CharField(default='fas fa-certificate', max_length=50)),
                ('feature4_title', models.CharField(default='Certification Provided', max_length=100)),
                ('feature4_description', models.TextField(default='Official recognition of your skills and expertise')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='academy/intro/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Priya Sharma', max_length=100)),
                ('role', models.CharField(default='Advanced Graduate', max_length=100)),
                ('content', models.TextField(default='SSV Academy transformed my hobby into a successful business.')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('avatar_color', models.CharField(default='#007bff', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
