# Generated by Django 5.2.7 on 2025-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_academybenefit_academycourse_academycta_academyhero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', help_text='Main banner title', max_length=200)),
                ('subtitle', models.TextField(default='Get in touch with us for inquiries, custom orders, or workshop registrations', help_text='Banner subtitle/description')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for contact banner', null=True, upload_to='contact/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutCTA',
        ),
    ]
