# Generated by Django 5.2.7 on 2025-10-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactherosection_delete_aboutcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student Name', max_length=100)),
                ('role', models.CharField(default='Course Graduate', max_length=100)),
                ('video', models.FileField(blank=True, help_text='Upload student testimonial video', null=True, upload_to='testimonials/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image for the video', null=True, upload_to='testimonials/thumbnails/')),
                ('description', models.TextField(blank=True, help_text='Optional description or quote', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
