# Generated by Django 5.2.7 on 2025-10-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studenttestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestimonial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studenttestimonial',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studenttestimonial',
            name='thumbnail',
        ),
    ]
