# Generated by Django 5.2.7 on 2025-10-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_studenttestimonial_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Large banner image for collection header', null=True, upload_to='collections/banners/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('contemporary', 'Contemporary'), ('bridal', 'Bridal'), ('casual', 'Casual'), ('premium', 'Premium')], default='traditional', max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='collection',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., ₹2,500 - ₹15,000', max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for cards', max_length=200),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', unique=True),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product Name', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name')),
                ('image', models.ImageField(help_text='Main product image', upload_to='collection_items/')),
                ('hover_image', models.ImageField(blank=True, help_text='Image shown on hover', null=True, upload_to='collection_items/hover/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in ₹', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discount', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('short_description', models.CharField(blank=True, help_text='Short description for cards', max_length=150)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured product in collection')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.collection')),
            ],
            options={
                'ordering': ['collection', 'order'],
            },
        ),
    ]
