# Generated by Django 5.2.7 on 2025-10-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_collection_banner_image_collection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.AddField(
            model_name='arrival',
            name='description',
            field=models.TextField(default='Beautiful AARI embroidery piece showcasing traditional craftsmanship.'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(default='Exquisite AARI designs showcasing traditional craftsmanship and modern aesthetics.'),
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
    ]
