# Generated by Django 5.2.7 on 2025-10-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_collection_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='whatsapp_message',
            field=models.TextField(default="Hi! I'm interested in {product_name}. Price: ₹{price}. Could you please provide more details?", help_text='WhatsApp message template. Use {product_name} and {price} as placeholders.'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='button_text',
            field=models.CharField(default='Enquire on WhatsApp', max_length=50),
        ),
    ]
