# Generated by Django 5.2.7 on 2025-10-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_arrival_whatsapp_message_alter_arrival_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='+917639027885', help_text='WhatsApp business number (include country code, e.g., +91 for India)', max_length=20)),
                ('business_name', models.CharField(default='SSV AARI WORK', help_text='Business name for WhatsApp messages', max_length=100)),
                ('default_enquiry_message', models.TextField(default='Hi! I would like to enquire about {product_name}. Price: ₹{price}. Please provide more details and availability.', help_text='Default WhatsApp message template. Use {product_name} and {price} as placeholders.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='StudentTestimonial',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='whatsapp_message',
        ),
        migrations.AlterField(
            model_name='arrival',
            name='button_text',
            field=models.CharField(default='Enquiry Now', max_length=50),
        ),
    ]
