# Generated by Django 5.2.7 on 2025-10-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_delete_studenttestimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Customer Name', max_length=100)),
                ('content', models.TextField(default='Amazing service and quality work!')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
