# Generated by Django 5.2.7 on 2025-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_hometestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometestimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='hometestimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload customer testimonial video', null=True, upload_to='testimonials/videos/'),
        ),
    ]
