# Generated by Django 5.2.7 on 2025-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_hometestimonial_image_hometestimonial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometestimonial',
            name='video_title',
            field=models.CharField(blank=True, default='', help_text='Title to display for the testimonial video', max_length=150),
        ),
    ]
