# Generated by Django 5.2.7 on 2025-11-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_sitesettings_hometestimonial_video_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
